nvim: show only first line of diagnostics' virtual_text
This is mainly because I want to capture the full gcc diagnostics

```
main.cpp: In function 'int main()':
main.cpp:8:12: error: 'squaree' was not declared in this scope; did you mean 'square'?
    8 |     return squaree(3);
      |            ^~~~~~~
      |            square
```

but I don't want it in the virtual text